---
packetbeat_package_names: packetbeat
packetbeat_package_state: present
packetbeat_conf_manage: yes
packetbeat_conf_path: /etc/packetbeat/packetbeat.yml
packetbeat_service_name: packetbeat
packetbeat_service_status: started
packetbeat_service_enabled: yes
packetbeat_repo_manage: yes
packetbeat_package_hold: no

packetbeat_conf_flows:
  timeout: 60s
  period: 10s

packetbeat_conf_protocols:
  - type: icmp
    enabled: true

  - type: dhcpv4
    ports: "{{ packetbeat_conf_protocols_dhcpv4_ports | default([67, 68]) }}"

  - type: dns
    ports: "{{ packetbeat_conf_protocols_dns_ports | default([53]) }}"

  - type: http
    ports: "{{ packetbeat_conf_protocols_http_ports | default([80]) }}"

  - type: tls
    ports: "{{ packetbeat_conf_protocols_tls_ports | default([443]) }}"

  - type: pgsql
    ports: "{{ packetbeat_conf_protocols_pgsql_ports | default([5432]) }}"

  - type: mysql
    ports: "{{ packetbeat_conf_protocols_mysql_ports | default([3306]) }}"

  - type: cassandra
    ports: "{{ packetbeat_conf_protocols_cassandra_ports | default([9042]) }}"

  - type: amqp
    ports: "{{ packetbeat_conf_protocols_amqp_ports | default([5072]) }}"

  - type: memcache
    ports: "{{ packetbeat_conf_protocols_memcache_ports | default([11211]) }}"

  - type: thrift
    ports: "{{ packetbeat_conf_protocols_thrift_ports | default([9090]) }}"

packetbeat_conf_extra: {}

packetbeat_conf_elasticsearch_enabled: true
packetbeat_conf_elasticsearch_port: 9200
packetbeat_conf_elasticsearch_hosts: ['localhost']
packetbeat_conf_elasticsearch_loadbalance: true

packetbeat_conf_logstash_enabled: false
packetbeat_conf_logstash_port: 5044
packetbeat_conf_logstash_hosts: ['localhost']
packetbeat_conf_logstash_loadbalance: true

packetbeat_conf_output_elasticsearch:
  enabled: "{{ packetbeat_conf_elasticsearch_enabled }}"
  hosts: "{{ packetbeat_conf_elasticsearch_hosts | map('map_format', '%s:' + (packetbeat_conf_elasticsearch_port | string)) | list }}"
  loadbalance: "{{ packetbeat_conf_elasticsearch_loadbalance }}"

packetbeat_conf_output_logstash:
  enabled: "{{ packetbeat_conf_logstash_enabled }}"
  hosts: "{{ packetbeat_conf_logstash_hosts | map('map_format', '%s:' + (packetbeat_conf_logstash_port | string)) | list }}"
  loadbalance: "{{ packetbeat_conf_logstash_loadbalance }}"

packetbeat_conf_output:
  elasticsearch: "{{ packetbeat_conf_output_elasticsearch }}"
  logstash: "{{ packetbeat_conf_output_logstash }}"

packetbeat_conf_setup:
  dashboards:
    enabled: "{{ packetbeat_conf_dashboards_enabled | default(false) }}"
    beat: packetbeat
    always_kibana: "{{ packetbeat_conf_dashboards_kibana | default(true) }}"
  template:
    enabled: "{{ packetbeat_conf_template_enabled | default(true) }}"
  kibana:
    host: "{{ packetbeat_conf_kibana_host | default('localhost:80') }}"

packetbeat_conf_base:
  packetbeat:
    interfaces:
      devices: any
      type: af_packet
    protocols: "{{ packetbeat_conf_protocols }}"
    flows: "{{ packetbeat_conf_flows }}"
  output: "{{ packetbeat_conf_output }}"
  setup: "{{ packetbeat_conf_setup }}"

packetbeat_conf: "{{ packetbeat_conf_base | combine(packetbeat_conf_extra) }}"
