---
name: lint
permissions:
  contents: read

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: "nephelaiio.packetbeat"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.packetbeat"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true
          project-path: "nephelaiio.packetbeat"

      - name: Debug test environment
        run: devbox run -- make debug

      - name: Run molecule tests
        run: devbox run -- make lint
